from enum import Enum


class ConfigType(str, Enum):
    LLM_MODEL = 'LLM_MODEL'
    LLM_BASE_URL = 'LLM_BASE_URL'
    LLM_API_KEY = 'LLM_API_KEY'
    LLM_DEPLOYMENT_NAME = 'LLM_DEPLOYMENT_NAME'
    LLM_API_VERSION = 'LLM_API_VERSION'
    LLM_NUM_RETRIES = 'LLM_NUM_RETRIES'
    LLM_COOLDOWN_TIME = 'LLM_COOLDOWN_TIME'
    LLM_EMBEDDING_STRATEGY = 'LLM_EMBEDDING_STRATEGY'
    LLM_EMBEDDING_MODEL = 'LLM_EMBEDDING_MODEL'
    LLM_EMBEDDING_BASE_URL = 'LLM_EMBEDDING_BASE_URL'
    LLM_EMBEDDING_API_KEY = 'LLM_EMBEDDING_API_KEY'
    LLM_EMBEDDING_DEPLOYMENT_NAME = 'LLM_EMBEDDING_DEPLOYMENT_NAME'
    LLM_EMBEDDING_API_VERSION = 'LLM_EMBEDDING_API_VERSION'
    WORKSPACE_DIR = 'WORKSPACE_DIR'
    SANDBOX_CONTAINER_IMAGE = 'SANDBOX_CONTAINER_IMAGE'
    RUN_AS_DEVIN = 'RUN_AS_DEVIN'
    DIRECTORY_REWRITE = 'DIRECTORY_REWRITE'
    MAX_ITERATIONS = 'MAX_ITERATIONS'
    AGENT = 'AGENT'
    SANDBOX_TYPE = 'SANDBOX_TYPE'
